name: Shlang CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build all
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/<YOUR_USERNAME>/<IMAGE_NAME>:<IMAGE_TAG>
      credentials:
        username: epanteleev
        password: ${{ secrets.GH_TOKEN }}
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4.1.5
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3.3.2
    - name: Run unit tests
      run: gradle :opt:jvmTest :shlang:jvmTest
    - name: Run testcases
      continue-on-error: true
      run: gradle :testcases:jvmTest
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: build-artifacts
        path: |
          shlang/build/
          opt/build/
