name: Shlang CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4.1.5
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
    - name: Build all
      run: gradle build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: build-artifacts
        path: |
          shlang/build/
          ssa/build/
