name: Shlang CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4.1.5
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3.3.2
    - name: Build all
      run: gradle :ssa:build :shlang:build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: build-artifacts
        path: |
          shlang/build/
          ssa/build/
  
